version: '3'

services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_DB: laravel-users-crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel-users-crud
      DB_USERNAME: postgres
      DB_PASSWORD: changeme
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata:
