version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: laravel-users-crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
