- hosts: all
  become: yes
  tasks:

    - name: Stop and remove old container (if exists)
      community.docker.docker_container:
        name: laravel_app
        state: absent

    - name: Remove old Docker image
      community.docker.docker_image:
        name: rommaa/laravel-users-crud
        tag: latest
        force_absent: yes
        state: absent

    - name: Pull Docker image
      community.docker.docker_image:
        name: rommaa/laravel-users-crud
        tag: latest
        source: pull

    - name: Run new Docker container
      community.docker.docker_container:
        name: laravel_app
        image: rommaa/laravel-users-crud:latest
        restart_policy: always
        ports:
          - '8000:8000'
        env:
          APP_ENV: production
          DB_CONNECTION: sqlite

    - name: Execute all setup commands
      community.docker.docker_container_exec:
        container: laravel_app
        command: >
          /bin/sh -c "
          cp -n .env.example .env &&
          php artisan key:generate &&
          touch /var/www/html/database/database.sqlite &&
          composer install --optimize-autoloader &&
          php artisan migrate --force &&
          php artisan db:seed --force &&
          php artisan storage:link &&
          npm ci &&
          npm run prepare &&
          npm run build
          "

    - name: Start Laravel server
      community.docker.docker_container_exec:
        container: laravel_app
        command: php artisan serve
