- hosts: all
  tasks:
    - name: Install Python and Docker dependencies
      apt:
        name:
          - python3-pip
          - docker.io
        update_cache: yes

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Pull Docker image
      community.docker.docker_image:
        name: "rommaa/laravel-users-crud:{{ version }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: app
        image: "rommaa/laravel-users-crud:{{ version }}"
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
        env:
          APP_ENV: production
          DB_CONNECTION: pgsql
          DB_HOST: db
          DB_PORT: 5432
          DB_DATABASE: laravel-users-crud
          DB_USERNAME: postgres
          DB_PASSWORD: changeme
