- hosts: all
  become: yes
  tasks:
    - name: Pull Docker image for app
      community.docker.docker_image:
        name: rommaa/laravel-users-crud
        tag: latest
        source: pull

    - name: Pull Docker image for Caddy
      community.docker.docker_image:
        name: rommaa/laravel-caddy
        tag: latest
        source: pull

    - name: Create network
      community.docker.docker_network:
        name: laravel_network

    - name: Stop and remove old app container (if exists)
      community.docker.docker_container:
        name: laravel_app
        state: absent

    - name: Run new app container
      community.docker.docker_container:
        name: laravel_app
        image: rommaa/laravel-users-crud:latest
        restart_policy: always
        networks:
          - name: laravel_network

    - name: Stop and remove old Caddy container (if exists)
      community.docker.docker_container:
        name: caddy
        state: absent

    - name: Run new Caddy container
      community.docker.docker_container:
        name: caddy
        image: rommaa/laravel-caddy:latest
        restart_policy: always
        ports:
          - 80:80
          - 443:443
        networks:
          - name: laravel_network
