name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: rommaa/laravel-users-crud:test

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup
        run: make setup

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Build and push latest Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rommaa/laravel-users-crud:latest

      # - run: docker run --rm ${{ env.TEST_TAG }} make test  # Эта строка оставлена нетронутой
      # - run: docker run --rm ${{ env.TEST_TAG }} make lint  # Эта строка оставлена нетронутой
