name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: rommaa/laravel-users-crud

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Установка Docker Buildx
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      # Логин в DockerHub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Сборка и пуш Docker образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      # - name: Run tests
      #   run: docker run --rm ${{ env.DOCKER_IMAGE }}:latest php artisan test
      #
      # # Линтинг кода
      # - name: Run linter
      #   run: docker run --rm ${{ env.DOCKER_IMAGE }}:latest npm run lint
