name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: rommaa/laravel-users-crud:test

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: make setup

      - name: Fix code style
        run: make fix

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test

  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Build and push latest Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rommaa/laravel-users-crud:latest
