name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: rommaa/laravel-users-crud:test

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Setup
        run: make setup

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test

      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rommaa/laravel-users-crud:latest

      - name: Build and push Caddy
        uses: docker/build-push-action@v2
        with:
          context: ./services/caddy
          file: Dockerfile
          push: true
          tags: rommaa/laravel-caddy:latest

      # - run: docker run --rm ${{ env.TEST_TAG }} make test  # Эта строка оставлена нетронутой
      # - run: docker run --rm ${{ env.TEST_TAG }} make lint  # Эта строка оставлена нетронутой
