name: main
on:
  push:
    branches:
      - 'main'
env:
  TEST_TAG: rommaa/laravel-users-crud:test
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      # - run: docker run --rm ${{ env.TEST_TAG }} make test
      # - run: docker run --rm ${{ env.TEST_TAG }} make lint

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rommaa/laravel-users-crud:latest
